// <auto-generated />
using System;
using Discount.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.API.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20240810170110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Discount.API.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67d67cfa-cbc9-4a34-aff9-5825894b88aa"),
                            Amount = 50,
                            Description = "iPhoneX Discount",
                            ProductName = "iPhone X"
                        },
                        new
                        {
                            Id = new Guid("3e26ecec-b0ed-4477-acb1-cf4e99c2ea34"),
                            Amount = 10,
                            Description = "Samsung Galaxy S24 Discount",
                            ProductName = "Samsung Galaxy S24"
                        },
                        new
                        {
                            Id = new Guid("df940598-8683-451a-8df9-d293943748be"),
                            Amount = 20,
                            Description = "Nintendo Switch Discount",
                            ProductName = "Nintendo Switch"
                        },
                        new
                        {
                            Id = new Guid("4a27ace2-2847-4974-a0b7-ab29581959d8"),
                            Amount = 50,
                            Description = "Asus TUF A15 Discount",
                            ProductName = "Asus TUF A15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
