// <auto-generated />
using System;
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20240808172151_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c21da51-8bb8-4c85-83af-8b9246bf4f89"),
                            Amount = 50,
                            Description = "iPhoneX Discount",
                            ProductName = "iPhone X"
                        },
                        new
                        {
                            Id = new Guid("d85fb4e4-c70c-49d0-986a-c63dc4b1beed"),
                            Amount = 10,
                            Description = "Samsung Galaxy S24 Discount",
                            ProductName = "Samsung Galaxy S24"
                        },
                        new
                        {
                            Id = new Guid("0e4a3bf0-eb2c-4548-8ece-f7adcae210c0"),
                            Amount = 20,
                            Description = "Nintendo Switch Discount",
                            ProductName = "Nintendo Switch"
                        },
                        new
                        {
                            Id = new Guid("e81f7936-757a-4980-8965-3a3a583470b3"),
                            Amount = 50,
                            Description = "Asus TUF A15 Discount",
                            ProductName = "Asus TUF A15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
